title: Run and Roll
description: Injury free running
email: jane@therackhameffect.com
baseurl: www.run-and-roll.co.uk

#Build Settings

markdown: kramdown
permalink: pretty

port: 3000

sass:
    sass_dir: assets/css
    style: :compressed

#SEO Settings

seo:
  description: 'Run and Roll, injury free running.'
  rel-author: 'https://plus.google.com/+Runology'
  rel-publisher: 'https://plus.google.com/+Runology'
